## YAML Template.
runtime: nodejs10

instance_class: F2

env_variables:
  PORT: 8080
  APIKEY: "AIzaSyDrKXRexz1LVUguEacndEgdgfxeEPhKTsA"

handlers:
- url: /
  static_dir: public

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

